---
entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
providers:
  docker:
    exposedByDefault: false
    network: proxy
  file:
    directory: /etc/traefik/config
    watch: true
api:
  dashboard: true
  insecure: true

accessLog: {}
